### PR TITLE
Database sql

### PR DESCRIPTION
**Pull request by bmlarson12**
The database is now running an embedded h2 database.

### CODE REVIEW

**Comment by IsaacIzy** [comment]
I resolved conflicts with the master. I didn't take the time to test out your changes yet, but I did look at the user changes, and that seems like the toString() will be a decent way to print user profiles on the client end. You want to fill us in on the general functionality on slack and then we can merge?

**Comment by bmlarson12** [comment]
Alright.

**Comment by IsaacIzy** [comment]
I did run all the unit tests and they pass no problem

**Comment by lsouth** [comment]
Looks good to me, I'm gonna go ahead and merge

**Pull request merged**
