### PR TITLE
Add game tests

### PR DESCRIPTION
**Pull request by lsouth**
I added a whole bunch of tests and implemented pretty much all of the game rules -- I think I'm pretty close to being finished with game implementation stuff at this point.

### CODE REVIEW

**Comment by IsaacIzy** [comment]
Mostly looks good. I'm getting the weird error about the diamond operator not being supported still, but I had fixed that on my build, so I'm not too worried. One thing we should add to the game interface is getBoard() and updateBoard() to help with synchronizing the server and clients, some of the code I wrote is dependent on that.

**Comment by IsaacIzy** [comment]
What JRE are you using? I've been using jdk 1.8_151, and I think the mismatch may be causing the compiler errors.

**Comment by lsouth** [comment]
I think all the merge conflicts should be good, if someone could double check and merge that'd be great

**Comment by IsaacIzy** [comment]
I can't get the build to pass in my environment, but I think it may be a problem on my side. @tartona @mvpbobwang @bmlarson12 could you guys pull this into eclipse and make sure the build is passing?

**Comment by IsaacIzy** [comment]
Found the issue. Maven was defaulting to java 1.5 whenever the project was updated. I added a property to the maven build that ensures that it will use java 1.8, and everything is working now. I also removed all of the @Override annotations in JungleGame b/c you don't have to override interface contract methods.

**Pull request merged**
